var user0 = {
  id: 0,
  nickname: '하이머딩거',
  mannerlv: 30,
  following: 600,
  follower: '118K',
  tag: ['INFP', '이명박'],
  description: 'One in a Million! Hello We are TWICE \nLets TikTok with TWICE',
  icon: 1004,
  gamecharacter: '하이머딩거 코치',
  Lv: '230',
  solorank: 'P4',
  teamrank: 'G1',
  position: 'top',
  preSeason: 'S10 diamond',
  summary: {
    win: 13,
    lose: 7,
    point: 2.28,
    winrate: 68,
    kda: '7.4/7.5/9.7',
  },
  mostChampions: [
    {
      champion: '하이머딩거',
      win: 12,
      lose: 7,
      winrate: 63,
      point: 2.28,
      KDA: '7.4/7.5/9.7',
    },
    {
      champion: '블리츠크랭크',
      win: 0,
      lose: 1,
      winrate: 0,
      point: 1.6,
      KDA: '2/5/6',
    },
  ],
  Detail: [
    { champion: '하이머딩거', result: '패', KDA: '19/8/9', point: 3.5 },
    { champion: '하이머딩거', result: '승', KDA: '4/5/10', point: 2.8 },
    { champion: '하이머딩거', result: '승', KDA: '19/7/15', point: 4.86 },
    { champion: '하이머딩거', result: '승', KDA: '11/4/8', point: 4.75 },
    { champion: '하이머딩거', result: '승', KDA: '8/4/10', point: 4.5 },
  ],
  achievement: '최근 업적 목록 1',
};
var user1 = {
  id: 1,
  nickname: '김고졸',
  mannerlv: 30,
  following: 600,
  follower: '100K',
  tag: ['INFP', '이명박'],
  description: 'One in a Million! Hello We are TWICE \nLets TikTok with TWICE',
  icon: 1005,
  gamecharacter: '김고졸의롤아이디',
  Lv: '156',
  solorank: 'S1',
  teamrank: 'I3',
  position: 'jug',
  preSeason: 'S9 gold',
  summary: {
    win: 13,
    lose: 7,
    point: 2.28,
    winrate: 68,
    kda: '7.4/7.5/9.7',
  },
  mostChampions: [
    {
      champion: '하이머딩거',
      win: 12,
      lose: 7,
      winrate: 63,
      point: 2.28,
      KDA: '7.4/7.5/9.7',
    },
    {
      champion: '블리츠크랭크',
      win: 0,
      lose: 1,
      winrate: 0,
      point: 1.6,
      KDA: '2/5/6',
    },
  ],
  Detail: [
    { champion: '하이머딩거', result: '패', KDA: '19/8/9', point: 3.5 },
    { champion: '하이머딩거', result: '승', KDA: '4/5/10', point: 2.8 },
    { champion: '하이머딩거', result: '승', KDA: '19/7/15', point: 4.86 },
    { champion: '하이머딩거', result: '승', KDA: '11/4/8', point: 4.75 },
    { champion: '하이머딩거', result: '승', KDA: '8/4/10', point: 4.5 },
  ],
  achievement: '최근 업적 목록 2',
};

var user2 = {
  id: 2,
  nickname: '스크림도르',
  mannerlv: 30,
  following: 600,
  follower: '100K',
  tag: ['INFP', '이명박'],
  description: 'One in a Million! Hello We are TWICE \nLets TikTok with TWICE',
  icon: 1007,
  gamecharacter: 'IIiiiIIIiI',
  Lv: '257',
  solorank: 'D2',
  teamrank: 'M',
  position: 'mid',
  preSeason: 'S11 bronze',
  summary: {
    win: 13,
    lose: 7,
    point: 2.28,
    winrate: 68,
    kda: '7.4/7.5/9.7',
  },
  mostChampions: [
    {
      champion: '하이머딩거',
      win: 12,
      lose: 7,
      winrate: 63,
      point: 2.28,
      KDA: '7.4/7.5/9.7',
    },
    {
      champion: '블리츠크랭크',
      win: 0,
      lose: 1,
      winrate: 0,
      point: 1.6,
      KDA: '2/5/6',
    },
  ],
  Detail: [
    { champion: '하이머딩거', result: '패', KDA: '19/8/9', point: 3.5 },
    { champion: '하이머딩거', result: '승', KDA: '4/5/10', point: 2.8 },
    { champion: '하이머딩거', result: '승', KDA: '19/7/15', point: 4.86 },
    { champion: '하이머딩거', result: '승', KDA: '11/4/8', point: 4.75 },
    { champion: '하이머딩거', result: '승', KDA: '8/4/10', point: 4.5 },
  ],
  achievement: '최근 업적 목록 3',
};

var user3 = {
  id: 3,
  nickname: '진수연',
  mannerlv: 30,
  following: 600,
  follower: '100K',
  tag: ['INFP', '이명박'],
  description: 'One in a Million! Hello We are TWICE \nLets TikTok with TWICE',
  icon: 1011,
  Lv: '78',
  gamecharacter: '부처님의 은혜',
  solorank: 'G3',
  teamrank: 'B3',
  position: 'bot',
  preSeason: 'S2 challenger',
  summary: {
    win: 13,
    lose: 7,
    point: 2.28,
    winrate: 68,
    kda: '7.4/7.5/9.7',
  },
  mostChampions: [
    {
      champion: '하이머딩거',
      win: 12,
      lose: 7,
      winrate: 63,
      point: 2.28,
      KDA: '7.4/7.5/9.7',
    },
    {
      champion: '블리츠크랭크',
      win: 0,
      lose: 1,
      winrate: 0,
      point: 1.6,
      KDA: '2/5/6',
    },
  ],
  Detail: [
    { champion: '하이머딩거', result: '패', KDA: '19/8/9', point: 3.5 },
    { champion: '하이머딩거', result: '승', KDA: '4/5/10', point: 2.8 },
    { champion: '하이머딩거', result: '승', KDA: '19/7/15', point: 4.86 },
    { champion: '하이머딩거', result: '승', KDA: '11/4/8', point: 4.75 },
    { champion: '하이머딩거', result: '승', KDA: '8/4/10', point: 4.5 },
  ],
  achievement: '최근 업적 목록 4',
};

var user4 = {
  id: 4,
  nickname: '수연이오빠',
  mannerlv: 30,
  following: 600,
  follower: '100K',
  tag: ['INFP', '이명박'],
  description: 'One in a Million! Hello We are TWICE \nLets TikTok with TWICE',
  icon: 1021,
  gamecharacter: '딩거르디움',
  Lv: '512',
  solorank: 'UN',
  teamrank: 'GM',
  position: 'sup',
  preSeason: 'S5 iron',
  summary: {
    win: 13,
    lose: 7,
    point: 2.28,
    winrate: 68,
    kda: '7.4/7.5/9.7',
  },
  mostChampions: [
    {
      champion: '하이머딩거',
      win: 12,
      lose: 7,
      winrate: 63,
      point: 2.28,
      KDA: '7.4/7.5/9.7',
    },
    {
      champion: '블리츠크랭크',
      win: 0,
      lose: 1,
      winrate: 0,
      point: 1.6,
      KDA: '2/5/6',
    },
  ],
  Detail: [
    { champion: '하이머딩거', result: '패', KDA: '19/8/9', point: 3.5 },
    { champion: '하이머딩거', result: '승', KDA: '4/5/10', point: 2.8 },
    { champion: '하이머딩거', result: '승', KDA: '19/7/15', point: 4.86 },
    { champion: '하이머딩거', result: '승', KDA: '11/4/8', point: 4.75 },
    { champion: '하이머딩거', result: '승', KDA: '8/4/10', point: 4.5 },
  ],
  achievement: '최근 업적 목록 5',
};

let users = [user0, user1, user2, user3, user4];

export default users;
